
jobs:
  - job: Ubuntu20GCC9DebugPart1
    displayName: "GCC9 debug on Ubuntu 20.04 (Part 1)"
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
      - template: devertexwahn/ci/ubuntu-20.04-gcc9-dbg-part1.yaml

  - job: Ubuntu20GCC9DebugPart2
    displayName: "GCC9 debug on Ubuntu 20.04 (Part 2)"
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
      - template: devertexwahn/ci/ubuntu-20.04-gcc9-dbg-part2.yaml
      - task: CmdLine@2
        inputs:
          script: 'bazel test --config=gcc9 //...'